require File.dirname(__FILE__) + '/../spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MembersController do

  def mock_member(stubs={})
    @mock_member ||= mock_model(Member, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all members as @members" do
      Member.stub(:all) { [mock_member] }
      get :index
      assigns(:members).should eq([mock_member])
    end
  end

  describe "GET show" do
    it "assigns the requested member as @member" do
      Member.stub(:find_by_username).with("Username") { mock_member }
      get :show, :username => "Username"
      assigns(:member).should be(mock_member)
    end
  end

end
